import { EnemyRarity, SlainThreshold, type EnemyStats } from "./enemy.types";

export const ENEMY_LIST_AREA_1: Record<string, EnemyStats> = {
  SLIME: {
    name: "Slime",
    health: 10,
    currentHealth: 10,
    currencyDropReward: 1,
    attackDamage: 1,
    attackSpeed: 2000,
    icon: "../../../slime.png",
    rarity: EnemyRarity.common,
  },
  BLOB: {
    name: "Blob",
    health: 10,
    currentHealth: 10,
    currencyDropReward: 1,
    attackDamage: 1,
    attackSpeed: 2000,
    icon: "../../../slime.png",
    rarity: EnemyRarity.common,
  },
  SLUG: {
    name: "Slug",
    health: 15,
    currentHealth: 15,
    currencyDropReward: 2,
    attackDamage: 1,
    attackSpeed: 1000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  OOZE: {
    name: "Ooze",
    health: 15,
    currentHealth: 15,
    currencyDropReward: 2,
    attackDamage: 1,
    attackSpeed: 1000,
    icon: "../../../rat.png",
    rarity: EnemyRarity.rare,
  },
  GLOOP: {
    name: "Gloop",
    health: 15,
    currentHealth: 15,
    currencyDropReward: 2,
    attackDamage: 1,
    attackSpeed: 1000,
    icon: "../../../rat.png",
    rarity: EnemyRarity.rare,
  },
  GUNK: {
    name: "Gunk",
    health: 15,
    currentHealth: 15,
    currencyDropReward: 2,
    attackDamage: 1,
    attackSpeed: 1000,
    icon: "../../../rat.png",
    rarity: EnemyRarity.legendary,
  },
};

export const ENEMY_LIST_AREA_2: Record<string, EnemyStats> = {
  BEETLE: {
    name: "Beetle",
    health: 30,
    currentHealth: 30,
    currencyDropReward: 4,
    attackDamage: 2,
    attackSpeed: 800,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  CRICKET: {
    name: "Cricket",
    health: 30,
    currentHealth: 30,
    currencyDropReward: 4,
    attackDamage: 2,
    attackSpeed: 800,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  WORM: {
    name: "Worm",
    health: 50,
    currentHealth: 50,
    currencyDropReward: 4,
    attackDamage: 10,
    attackSpeed: 3000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  ANT: {
    name: "Ant",
    health: 50,
    currentHealth: 50,
    currencyDropReward: 4,
    attackDamage: 10,
    attackSpeed: 3000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  BEE: {
    name: "Bee",
    health: 50,
    currentHealth: 50,
    currencyDropReward: 4,
    attackDamage: 10,
    attackSpeed: 3000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  MOTH: {
    name: "Moth",
    health: 50,
    currentHealth: 50,
    currencyDropReward: 4,
    attackDamage: 10,
    attackSpeed: 3000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.legendary,
  },
};

export const ENEMY_LIST_AREA_3: Record<string, EnemyStats> = {
  PENGUIN: {
    name: "Penguin",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  BIRD: {
    name: "Snow Bird",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  POLAR_BEAR: {
    name: "Polar Bear",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  YETI: {
    name: "Snow Yeti",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  ORCA: {
    name: "Orca",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  LEOPARD: {
    name: "Snow Leopard",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.legendary,
  },
};

export const ENEMY_LIST_AREA_4: Record<string, EnemyStats> = {
  DRAGON: {
    name: "Dragon",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  CROCODILE: {
    name: "Crocodile",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  SNAKE: {
    name: "Snake",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  MINOTAUR: {
    name: "Minotaur",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  UNICORN: {
    name: "Unicorn",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  KING_SIMON: {
    name: "King Simon",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.legendary,
  },
};

export const ENEMY_LIST_AREA_5: Record<string, EnemyStats> = {
  DEMON: {
    name: "Demon",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  IMP: {
    name: "Imp",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  DEVIL: {
    name: "Devil",
    health: 60,
    currentHealth: 60,
    currencyDropReward: 10,
    attackDamage: 1,
    attackSpeed: 300,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.common,
  },
  ELEMENTAL: {
    name: "Elemental",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  DJINN: {
    name: "Djinn",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.rare,
  },
  ALMIGHTY_SIMON: {
    name: "ALmighty Simon",
    health: 200,
    currentHealth: 200,
    currencyDropReward: 20,
    attackDamage: 30,
    attackSpeed: 5000,
    icon: "../../../goblin.png",
    rarity: EnemyRarity.legendary,
  },
};

export const RARITY_WEIGHTS: Record<EnemyRarity, number> = {
  [EnemyRarity.common]: 70, // 70% chance for common enemies
  [EnemyRarity.rare]: 20, // 8% chance for rare enemies
  [EnemyRarity.legendary]: 10, // 2% chance for legendary enemies
};

export const RARITY_THRESHOLDS: Record<
  EnemyRarity,
  Record<SlainThreshold, number>
> = {
  [EnemyRarity.common]: {
    [SlainThreshold.bronze]: 30,
    [SlainThreshold.silver]: 50,
    [SlainThreshold.gold]: 70,
  },
  [EnemyRarity.rare]: {
    [SlainThreshold.bronze]: 10,
    [SlainThreshold.silver]: 20,
    [SlainThreshold.gold]: 30,
  },
  [EnemyRarity.legendary]: {
    [SlainThreshold.bronze]: 3,
    [SlainThreshold.silver]: 5,
    [SlainThreshold.gold]: 10,
  },
};

export const ALL_ENEMIES: Record<string, EnemyStats> = {
  ...ENEMY_LIST_AREA_1,
  ...ENEMY_LIST_AREA_2,
  ...ENEMY_LIST_AREA_3,
  ...ENEMY_LIST_AREA_4,
  ...ENEMY_LIST_AREA_5,
};
