import type { ButtonPosition } from "./brain.types";

export const BRAIN_UPGRADES: ButtonPosition[] = [
  // Central button
  {
    id: 1,
    x: 50,
    y: 50,
    connectedTo: [2, 3, 4, 5, 6, 7, 8, 9],
    cost: 1,
    name: "Neural Core",
    description:
      "The center of your brain. Starting point for all upgrades.\n\n Unlocks 10% bonus to attack damage and health per brain cell point spent.\n\n Total bonus:",
  },

  // Middle nodes (between center and outer clusters) - Ring 2
  {
    id: 2,
    x: 50,
    y: 35,
    connectedTo: [10],
    cost: 1,
    name: "Exploration Instinct",
    description: "Unlocks the ability to go on adventures",
  },
  {
    id: 3,
    x: 35,
    y: 35,
    connectedTo: [14],
    cost: 1,
    name: "Tool Crafting Mind",
    description: "Unlocks the ability to craft tools",
  },
  {
    id: 4,
    x: 62.5,
    y: 38,
    connectedTo: [18],
    cost: 1,
    name: "Research Protocols",
    description: "Unlocks the research lab for discovering new technologies",
  },
  {
    id: 5,
    x: 67.5,
    y: 50,
    connectedTo: [21],
    cost: 1,
    name: "Trade Networks",
    description: "Unlocks the marketplace for buying and selling resources",
  },
  {
    id: 6,
    x: 62.5,
    y: 62,
    connectedTo: [24],
    cost: 1,
    name: "Guild Management",
    description: "Unlocks the ability to recruit and manage companions",
  },
  {
    id: 7,
    x: 50,
    y: 65,
    connectedTo: [27],
    cost: 1,
    name: "Territory Control",
    description: "Unlocks the ability to claim and upgrade territories",
  },
  {
    id: 8,
    x: 37.5,
    y: 62,
    connectedTo: [30],
    cost: 1,
    name: "Alchemy Knowledge",
    description: "Unlocks the alchemy system for brewing potions and elixirs",
  },
  {
    id: 9,
    x: 32.5,
    y: 50,
    connectedTo: [33],
    cost: 1,
    name: "Gene Splicing",
    description: "Unlocks mutation system for permanent upgrades",
  },

  // Top cluster - Ring 3 (10-13)
  {
    id: 10,
    x: 50,
    y: 18,
    connectedTo: [11, 12, 13],
    cost: 2,
    name: "Memory Core",
    description: "Greatly increases memory capacity by 25%",
  },
  {
    id: 11,
    x: 38,
    y: 10,
    connectedTo: [],
    cost: 3,
    name: "Short-term Memory",
    description: "Perfects short-term memory recall",
  },
  {
    id: 12,
    x: 50,
    y: 8,
    connectedTo: [],
    cost: 3,
    name: "Long-term Memory",
    description: "Perfects long-term memory storage",
  },
  {
    id: 13,
    x: 62,
    y: 10,
    connectedTo: [],
    cost: 3,
    name: "Photographic Memory",
    description: "Enables perfect visual memory",
  },

  // Top-left cluster - Ring 3 (14-17)
  {
    id: 14,
    x: 18,
    y: 18,
    connectedTo: [15, 16, 17],
    cost: 2,
    name: "Logic Core",
    description: "Greatly improves logical reasoning by 25%",
  },
  {
    id: 15,
    x: 10,
    y: 10,
    connectedTo: [],
    cost: 3,
    name: "Deductive Reasoning",
    description: "Masters deductive logic",
  },
  {
    id: 16,
    x: 20,
    y: 6,
    connectedTo: [],
    cost: 3,
    name: "Inductive Reasoning",
    description: "Masters inductive logic",
  },
  {
    id: 17,
    x: 6,
    y: 23,
    connectedTo: [],
    cost: 3,
    name: "Abstract Thinking",
    description: "Unlocks advanced abstract concepts",
  },

  // Right top cluster - Ring 3 (18-20)
  {
    id: 18,
    x: 78,
    y: 26,
    connectedTo: [19, 20],
    cost: 2,
    name: "Reflex Core",
    description: "Greatly enhances reaction time by 25%",
  },
  {
    id: 19,
    x: 88,
    y: 18,
    connectedTo: [],
    cost: 3,
    name: "Combat Reflexes",
    description: "Perfect combat reaction speed",
  },
  {
    id: 20,
    x: 92,
    y: 32,
    connectedTo: [],
    cost: 3,
    name: "Evasion Mastery",
    description: "Master-level dodge capabilities",
  },

  // Right cluster - Ring 3 (21-23)
  {
    id: 21,
    x: 88,
    y: 50,
    connectedTo: [22, 23],
    cost: 2,
    name: "Focus Core",
    description: "Greatly increases focus by 25%",
  },
  {
    id: 22,
    x: 94,
    y: 44,
    connectedTo: [],
    cost: 3,
    name: "Deep Concentration",
    description: "Achieve deep meditative focus",
  },
  {
    id: 23,
    x: 97,
    y: 56,
    connectedTo: [],
    cost: 3,
    name: "Flow State",
    description: "Enter the ultimate flow state",
  },

  // Right bottom cluster - Ring 3 (24-26)
  {
    id: 24,
    x: 78,
    y: 74,
    connectedTo: [25, 26],
    cost: 2,
    name: "Pattern Core",
    description: "Greatly improves pattern recognition by 25%",
  },
  {
    id: 25,
    x: 88,
    y: 82,
    connectedTo: [],
    cost: 3,
    name: "Predictive Analysis",
    description: "Predict future patterns accurately",
  },
  {
    id: 26,
    x: 92,
    y: 68,
    connectedTo: [],
    cost: 3,
    name: "Chaos Theory",
    description: "Understand complex chaotic systems",
  },

  // Bottom cluster - Ring 3 (27-29)
  {
    id: 27,
    x: 50,
    y: 82,
    connectedTo: [28, 29],
    cost: 2,
    name: "Motor Core",
    description: "Greatly enhances motor skills by 25%",
  },
  {
    id: 28,
    x: 38,
    y: 90,
    connectedTo: [],
    cost: 3,
    name: "Fine Motor Control",
    description: "Perfect precision in movements",
  },
  {
    id: 29,
    x: 62,
    y: 90,
    connectedTo: [],
    cost: 3,
    name: "Athletic Mastery",
    description: "Master-level athletic performance",
  },

  // Left bottom cluster - Ring 3 (30-32)
  {
    id: 30,
    x: 22,
    y: 74,
    connectedTo: [31, 32],
    cost: 2,
    name: "Creativity Core",
    description: "Greatly boosts creativity by 25%",
  },
  {
    id: 31,
    x: 12,
    y: 82,
    connectedTo: [],
    cost: 3,
    name: "Artistic Vision",
    description: "Unlock true artistic genius",
  },
  {
    id: 32,
    x: 8,
    y: 68,
    connectedTo: [],
    cost: 3,
    name: "Innovation Mind",
    description: "Generate revolutionary ideas",
  },

  // Left cluster - Ring 3 (33)
  {
    id: 33,
    x: 12,
    y: 50,
    connectedTo: [],
    cost: 2,
    name: "Polyglot",
    description: "Master multiple languages instantly",
  },
];
